[build]
command = "npm run build"
publish = "out"

[[redirects]]
from = "/msk-upper-quadrant-reference"
to = "/"
status = 200

[[redirects]]
from = "/msk-upper-quadrant-reference/"
to = "/"
status = 200

[[redirects]]
from = "/msk-upper-quadrant-reference/_next/*"
to = "/_next/:splat"
status = 200

[[redirects]]
from = "/msk-upper-quadrant-reference/*"
to = "/:splat"
status = 200
